### ISSUE TITLE
Terrain-RGB error

### ISSUE THREAD

**Issue by webmap2015** [acalcutt/jaxa_AW3D30_to_MBTiles#1]
Hi,

While creating terrain-rgb, there is an error:

rasterio.errors.CRSError: The PROJ4 dict could not be understood. PROJ: proj_create: cannot expand init='epsg:3857' +type=crs

What is your versions of
ubuntu
gdal
rasterio
rio-rgbify?

Thanks.

**Comment by acalcutt** [comment]
I am running in debian 11 here. I set up my base server using this script for my other project, which installs a bunch of mapping tools, like proj and gdal ( https://github.com/acalcutt/wdb-map-gen/blob/planetiler/tools/install_tools.sh ). 

It looks like that script is installing proj-8.2.1.tar.gz and gdal-3.4.1.tar.gz

rio-rgbify I just installed the latest using pip (installing python with pip is part of my install_tools.sh if you don't already have it)

**Comment by acalcutt** [comment]
Also to note, If using the jaxa images, I would only go to zoom level 12. the zoom level 14 in the script on the repository is a bit much and likely won't add any better resolution.

With zoom level 12, the full planet comes out to around 465GB, but when at zoom 14 it will likely be very large (i never finished my Z14 tiles, but it got up to 1.5TB before i decided Z12 was good)...it would proably be 2TB+ (you have to figure, each zoom level has 4X more images than the previous layer, so that takes space)

**Comment by webmap2015** [comment]
Thanks.

**Comment by webmap2015** [comment]
Hi,

After running "create_terrainrgb.sh", it creates mbtiles but it gives an warning.

![Capture](https://user-images.githubusercontent.com/10267317/166132235-c4bcc2fb-4b63-4d4a-8e33-d6b77d82135e.PNG)

Do you have the same warning?

Thanks.

**Comment by acalcutt** [comment]
Yes, those warning should be fine. I got them too but mine was successful. you can always start with one image and test it out first.

**Comment by acalcutt** [comment]
I just wanted to let you know I regenerated a new planet mbtiles with this process and have updated a few of the scripts, if you have not seen that already.

I've lowered the proj version in https://github.com/acalcutt/wdb-map-gen/blob/planetiler/tools/install_tools.sh to proj-7.2.1.tar.gz to fix "free()" errors I was seeing. I found some things in gdal did not like the newer version of proj I mentioned before. This process still worked even with the free() errors, but I had other processes that didn't.

I've updated https://github.com/acalcutt/jaxa_AW3D30_to_MBTiles/blob/main/create_terrainrgb.sh to default to zoom 12 and add in metadata

I've updated the list of DEM zip files , so it should now be complete at https://github.com/acalcutt/jaxa_AW3D30_to_MBTiles/blob/main/file_list_zip.txt . this is used by https://github.com/acalcutt/jaxa_AW3D30_to_MBTiles/blob/main/download_zips.sh 

I also wanted to mention this speedup I did on my local rio rgbify.  I customized my local rio-rgbify to include this PR to speed up mbtiles generations ( https://github.com/mapbox/rio-rgbify/pull/29 ) at https://github.com/acalcutt/rio-rgbify/ . The first time I generated the full planet it took me something like 21 days for the mbtiles creation. with the fix from the PR (using wal mode) it took 4 days for the full planet.

**Comment by webmap2015** [comment]
Thanks.

**Comment by kannes** [comment]
Adding the `NotGeoreferencedWarning` warning as text so search engines can pick it up:
"`NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.`"

**Comment by webmap2015** [comment]
Thanks.
